name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.6.0
    with:
      env: '["py39", "py310", "py311", "py312"]'
      os: ubuntu-latest

